config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resource :users, only: [:edit, :update]
  get "signup" => "users#new"
  post 'signup' => "users#create"
  get "mypage" => "users#show", as: "mypage"
  delete "mypage" => "users#destroy", as: "unsubscribe"

  resources :zombies do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end

  get "search" => "zombies#search"

  get 'diagnose' => "diagnose#new"
  get 'diagnose/index' => "diagnose#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/diagnose_controller.rb
class DiagnoseController < ApplicationController
  def new
  end

  def index

      #ゾンビと何したい？
      if params[:q_1] == 'a' #ゾンビを鑑賞したい
        zombies_1 = Zombie.includes(:tags).where(tags: {name: "映画"}).or(Zombie.includes(:tags).where(tags: {name: "ドラマ"}))
      elsif params[:q_1] == 'b' #ゾンビと遊びたい
        zombies_1 = Zombie.includes(:tags).where(tags: {name: "ゲーム"}).or(Zombie.includes(:tags).where(tags: {name: "スマホアプリ"}))
      end
      s1 = zombies_1.ids.uniq #該当するゾンビidの配列
      
      # どっちのゾンビが好き？
      if params[:q_2] == 'a' #怖いゾンビ
        zombies_2 = Zombie.includes(:tags).where(tags: {name: "こわい"}).or(Zombie.includes(:tags).where(tags: {name: "ホラー"}))
      elsif params[:q_2] == 'b' #かわいいゾンビ
        zombies_2 = Zombie.includes(:tags).where(tags: {name: "かわいい"}).or(Zombie.includes(:tags).where(tags: {name: "シュール"}))
      end
      s2 = zombies_2.ids.uniq #該当するゾンビidの配列
      
      # ゾンビと何したい？
      if params[:q_3] == 'a' #ゾンビと戦いたい
        zombies_3 = Zombie.includes(:tags).where(tags: {name: "パニック"}).or(Zombie.includes(:tags).where(tags: {name: "アクション"}))
      elsif params[:q_3] == 'b' #ゾンビと仲良くなりたい
        zombies_3 = Zombie.includes(:tags).where(tags: {name: "恋愛"}).or(Zombie.includes(:tags).where(tags: {name: "青春"}))
      end
      s3 = zombies_3.ids.uniq #該当するゾンビidの配列
      
      # ゾンビとの接し方は？
      if params[:q_4] == 'a' #サクッと
        zombies_4 = Zombie.includes(:tags).where(tags: {name: "映画"}).or(Zombie.includes(:tags).where(tags: {name: "スマホアプリ"}))
      elsif params[:q_4] == 'b' #長期的に
        zombies_4 = Zombie.includes(:tags).where(tags: {name: "ドラマ"}).or(Zombie.includes(:tags).where(tags: {name: "ゲーム"}))
      end
      s4 = zombies_4.ids.uniq #該当するゾンビidの配列
      
      #質問から取得したゾンビidの配列を結合
      total = s1 << s2 << s3 << s4
      total.flatten!
      #「重複回数＝質問の数」のidを取得
      total_s = total.select{ |e| total.count(e) == 4}.uniq
      @zombies = Zombie.where id: total_s

  end

  private

  def diagnose_params
    params.require(:diagnose).permit(tag_ids: [])
  end


end

app/helpers/diagnose_helper.rb
module DiagnoseHelper
end

app/views/diagnose/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center align-items-center" style="height: 100px;">
    <h1>アナタにおすすめのゾンビ</h1>
  </div>

  <div class="row d-flex justify-content-center align-items-center">
    <div class="col-md-8">
      <table class="table table-sm">
        <thead>
          <tr>
            <th style="width: 25%"></th>
            <th style="width: 25%">タイトル</th>
            <th style="width: 50%">概　要</th>
          </tr>
        </thead>

        <tbody>
          <% @zombies.each do |zombie| %>
            <tr>
              <td><%= attachment_image_tag zombie, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
                  <span>お気に入り数(<%= zombie.favorites.length %>)</span></td>
              <td><%= link_to zombie.name, zombie_path(zombie), class:"text-dark" %></td>
              <td><%= zombie.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="row d-flex justify-content-center align-items-center">
    <%= link_to "TOPへ戻る", root_path, class:"btn btn-sm btn-outline-info mr-4" %>
    <%= link_to "一覧をみる", zombies_path, class:"btn btn-sm btn-outline-info" %>
  </div>
</div>

app/views/diagnose/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center align-items-center" style="height: 100px;">
    <h1>診断ページ</h1>
  </div>

  <div class="row d-flex flex-column justify-content-center align-items-center">
    <%= form_with url: diagnose_index_path, method: :get, local: true do |f| %>

    <table>
      <th><strong>１.ゾンビと何したい？</strong></th>
      <tr>
        <td><%= f.radio_button :q_1, "a", checked: true %><%= f.label :q_1_a, "ゾンビを鑑賞したい" %></td>
        <td><%= f.radio_button :q_1, "b" %><%= f.label :q_1_b, "ゾンビと遊びたい" %></td>
      </tr>

      <th><strong>２.どっちのゾンビが好き？</strong></th>
      <tr>
        <td><%= f.radio_button :q_2, "a", checked: true %><%= f.label :q_2_a, "怖いゾンビ" %></td>
        <td><%= f.radio_button :q_2, "b" %><%= f.label :q_2_b, "かわいいゾンビ" %></td>
      </tr>

      <th><strong>３.ゾンビと何したい？</strong></th>
      <tr>
        <td><%= f.radio_button :q_3, "a", checked: true %><%= f.label :q_3_a, "ゾンビと戦いたい" %></td>
        <td><%= f.radio_button :q_3, "b" %><%= f.label :q_3_b, "ゾンビと仲良くなりたい" %></td>
      </tr>

      <th><strong>４.ゾンビとの接し方は？</strong></th>
      <tr>
        <td><%= f.radio_button :q_4, "a", checked: true %><%= f.label :q_4_a, "サクッと" %></td>
        <td><%= f.radio_button :q_4, "b" %><%= f.label :q_4_b, "長期的に" %></td>
      </tr>
    </table>

      <div class="d-flex justify-content-center align-items-center mt-3">
        <%= f.submit "診断結果へ", class:"btn btn-sm btn-outline-info" %>
      </div>

    <% end %>
  </div>
</div>