config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resource :users, only: [:edit, :update]
  get "signup" => "users#new"
  post 'signup' => "users#create"
  get "mypage" => "users#show", as: "mypage"
  delete "mypage" => "users#destroy", as: "unsubscribe"

  resources :zombies do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end

  get "search" => "zombies#search"

  get 'diagnose' => "diagnose#new"
  get 'diagnose/index' => "diagnose#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,  length: { maximum: 200 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_secure_password


  has_many :favorites, dependent: :destroy
  has_many :reviwes, dependent: :destroy
  has_many :zombies, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :edit, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to mypage_path(@user)
    else
      render 'new'
    end
  end

  def show
    @favorites = Favorite.where(user_id: current_user.id)
    @reviews = Review.where(user_id: current_user.id)
    @zombies = Zombie.where(user_id: current_user.id)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to mypage_path
    else
      render 'edit'
    end
  end

  def destroy
    current_user.destroy
    redirect_to signup_path
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
 
end

app/views/users/edit.html.erb
<div class="container">

  <div class="row d-flex justify-content-center align-items-center" style="height: 100px;">
    <h1>ユーザー情報編集</h1>
  </div>
    
  <div class="row d-flex flex-column justify-content-center align-items-center">
    <%= form_with model: current_user, url: users_path, local: true do |f| %>
     
        <div class="d-flex flex-column justify-content-center align-items-center text-danger">
          <% if current_user.errors.any? %>
            <strong><%= current_user.errors.count %>個のエラーがあります。</strong>
              <ul>
                <% current_user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
          <% end %>
        </div>

      <table class="table table-borderless">
        <tr>
          <th><%= f.label :name, "ニックネーム" %></th>
          <td><%= f.text_field :name %></td>
        </tr>
        
        <tr>
          <th><%= f.label :email, 'メールアドレス' %></th>
          <td><%= f.email_field :email %></td>
        </tr>
      </table>
    
    <div class="row d-flex justify-content-center align-items-center">
      <%= f.submit "この内容で保存する", class:"btn btn-outline-info btn-sm" %>
    </div>
    <div class="row d-flex justify-content-center align-items-center m-3">
      <%= link_to "退会する", unsubscribe_path, method: :delete, data: { confirm: '本当に退会しますか？' }, class:"btn btn-outline-danger btn-sm" %>
    </div>
    
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">

  <div class="row d-flex justify-content-center align-items-center" style="height: 100px;">
    <h1>ユーザー登録</h1>
  </div>
    
    
  <div class="row d-flex flex-column justify-content-center align-items-center">
     <%= form_with model: @user, url: signup_path, local: true do |f| %>
     
        <div class="d-flex flex-column justify-content-center align-items-center text-danger">
          <% if @user.errors.any? %>
            <strong><%= @user.errors.count %>個のエラーがあります。</strong>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
          <% end %>
        </div>
      
      <table class="table table-borderless">
        <tr>
          <th><%= f.label :name, 'ニックネーム' %></th>
          <td><%= f.text_field :name %></td>
        </tr>
        
        <tr>
          <th><%= f.label :email, 'メールアドレス' %></th>
          <td><%= f.email_field :email %></td>
        </tr>

        <tr>
          <th><%= f.label :password, 'パスワード（６文字以上）' %></th>
          <td><%= f.password_field :password %></td>
        </tr>
        
        <tr>
          <th><%= f.label :password_confirmation, 'パスワード(確認)' %></th>
          <td><%= f.password_field :password_confirmation %></td>
        </tr>
      </table>    
      
      <div class="row d-flex justify-content-center align-items-center">
        <%= f.submit '登録', class:"btn btn-info" %>
      </div>
        
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row d-flex justify-content-center align-items-center" style="height: 100px;">
    <h1>ユーザー情報</h1>
  </div>

  <div class="row d-flex justify-content-center align-items-center" style="height: 100px;">
    <div>
      <table class="table table-borderless">
        <tr>
          <th>ニックネーム：</th>
          <td><%= current_user.name %></td>

          <th>メールアドレス：</th>
          <td><%= current_user.email %></td>

          <td><%= link_to "編 集", edit_users_path, class:"btn btn-outline-primary btn-sm" %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 d-flex flex-column justify-content-center align-items-center">
      <div class="m-3">
        <span>投稿一覧</span>
      </div>

      <div>
      <% if @zombies.present? %>
        <table class="table table-sm">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>概  要</th>
            </tr>
          </thead>

          <tbody>
            <% @zombies.each do |zombie| %>
            <tr>
              <td><%= link_to zombie.name, zombie_path(zombie), class:"text-dark" %></td>
              <td><%= zombie.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <span>あなたの知っているゾンビコンテンツを投稿することができます</span>
      <% end %>
      </div>
      
      <div>
        <%= link_to "ゾンビを投稿", new_zombie_path, class:"btn btn-outline-info btn-sm m-3" %>
      </div>
    </div>

    <div class="col-md-4 d-flex flex-column justify-content-center align-items-center">
      <div class="m-3">
        <span>お気に入り一覧</span>
      </div>

      <div>
        <table class="table table-sm">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>概  要</th>
            </tr>
          </thead>
          
          <tbody>
            <% @favorites.each do |fav| %>
            <tr>
              <td><%= link_to fav.zombie.name, zombie_path(fav.zombie), class:"text-dark" %></td>
              <td><%= fav.zombie.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


    <div class="col-md-4 d-flex flex-column justify-content-center align-items-center">
      <div class="m-3">
        <span>レビュー投稿一覧</span>
      </div>

      <div>
        <table class="table table-sm">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>レビュー内容</th>
            </tr>
          </thead>

          <tbody>
            <% @reviews.each do |review| %>
            <tr>
              <td><%= link_to review.zombie.name, zombie_path(review.zombie), class:"text-dark" %></td>
              <td><%= review.body %></td>
              <td><%= link_to "削除", zombie_reviews_path(review.zombie), method: :delete,data: { confirm: '本当に削除しますか？' },class:"btn btn-sm btn-outline-danger" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>

</div>