config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resource :users, only: [:edit, :update]
  get "signup" => "users#new"
  post 'signup' => "users#create"
  get "mypage" => "users#show", as: "mypage"
  delete "mypage" => "users#destroy", as: "unsubscribe"

  resources :zombies do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end

  get "search" => "zombies#search"

  get 'diagnose' => "diagnose#new"
  get 'diagnose/index' => "diagnose#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/3e46d09fe1.js" crossorigin="anonymous"></script>

    <title>ZombieSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <body class="d-flex flex-column vh-100">
    <header>
    <div class="container">
      <nav class="navbar navbar-dark bg-dark fixed-top" >

      <h4><%= link_to "ゾンビさがし",root_path, class:"nabvar-brand text-light m-4" %></h4>

        <div class="search_form ml-auto mr-3">
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, value: @keyword, size: 15 %>
            <%= f.submit "検索", class:"btn btn-sm btn-light" %>
          <% end %>
        </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">

            <li class="nav-item ml-auto mr-3"><%= link_to"診断から探す", diagnose_path,class:"text-light" %></li>
            <li class="nav-item ml-auto mr-3"><%= link_to "一覧表示", zombies_path,class:"text-light" %></li>
            
          <% if logged_in? %>
            <li class="nav-item ml-auto mr-3"><%= link_to"マイページ", mypage_path,class:"text-light" %></li>
            <li class="nav-item ml-auto mr-3"><%= link_to"ログアウト", logout_path, method: :delete,class:"text-light" %></li>
          <% else %>
            <li class="nav-item ml-auto mr-3"><%= link_to"新規登録", signup_path,class:"text-light" %></li>
          <% end %>
        </ul>


       </div>

      </div>
      </nav>
    </header>

    <div>
    <%= yield %>
    </div>

  </body>
</html>